# ~/.config/matugen/templates/kitty.conf

foreground #dfe3e7
background #0f1417
selection_foreground #21333e
selection_background #b6c9d8

cursor #dfe3e7
cursor_text_color #0f1417

active_tab_foreground #0f1417
active_tab_background #91cef5
inactive_tab_foreground #dfe3e7
inactive_tab_background #41484d

# The 16 terminal colors
color0 #0f1417
color8 #41484d

color1 #ffb4ab
color9 #ffb4ab

color2 #91cef5
color10 #91cef5

color3 #b6c9d8
color11 #b6c9d8

color4 #ccc1e9
color12 #ccc1e9

color5 #206487
color13 #206487

color6 #c6e7ff
color14 #c6e7ff

color7 #dfe3e7
color15 #dfe3e7