# ~/.config/matugen/templates/kitty.conf

foreground #e2e2e9
background #121318
selection_foreground #2a3042
selection_background #c0c6dc

cursor #e2e2e9
cursor_text_color #121318

active_tab_foreground #121318
active_tab_background #b1c5ff
inactive_tab_foreground #e2e2e9
inactive_tab_background #44464f

# The 16 terminal colors
color0 #121318
color8 #44464f

color1 #ffb4ab
color9 #ffb4ab

color2 #b1c5ff
color10 #b1c5ff

color3 #c0c6dc
color11 #c0c6dc

color4 #e0bbdd
color12 #e0bbdd

color5 #485d92
color13 #485d92

color6 #dae2ff
color14 #dae2ff

color7 #e2e2e9
color15 #e2e2e9