# ~/.config/matugen/templates/kitty.conf

foreground #f0dedd
background #1a1111
selection_foreground #442928
selection_background #e7bdba

cursor #f0dedd
cursor_text_color #1a1111

active_tab_foreground #1a1111
active_tab_background #ffb3af
inactive_tab_foreground #f0dedd
inactive_tab_background #534342

# The 16 terminal colors
color0 #1a1111
color8 #534342

color1 #ffb4ab
color9 #ffb4ab

color2 #ffb3af
color10 #ffb3af

color3 #e7bdba
color11 #e7bdba

color4 #e3c28c
color12 #e3c28c

color5 #904a48
color13 #904a48

color6 #ffdad7
color14 #ffdad7

color7 #f0dedd
color15 #f0dedd