# Sedly-Rice Starship Prompt (Dynamic Matugen)

format = """
[╭─](bold #ffb3af)$directory$git_branch$git_status$character
[╰─](bold #ffb3af) """

right_format = """$cmd_duration$time"""

continuation_prompt = '[▶▶ ](bold #ffb3af)'

[directory]
style = "bold #ffb3af"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bold #e3c28c"
format = "on [$symbol$branch ]($style)"
symbol = "󰊢 "

[git_status]
style = "bold #ffb4ab"
format = "([$all_status$ahead_behind]($style) )"

[character]
success_symbol = "[❯](bold #ffb3af)"
error_symbol = "[❯](bold #ffb4ab)"

[time]
disabled = false
style = "bold #a08c8b"
format = "[$time]($style)"
time_format = "%T"

[cmd_duration]
style = "bold #e7bdba"
format = "took [$duration]($style) "
min_time = 2_000