# Sedly-Rice Starship Prompt (Dynamic Matugen)

format = """
[╭─](bold #b1c5ff)$directory$git_branch$git_status$character
[╰─](bold #b1c5ff) """

right_format = """$cmd_duration$time"""

continuation_prompt = '[▶▶ ](bold #b1c5ff)'

[directory]
style = "bold #b1c5ff"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bold #e0bbdd"
format = "on [$symbol$branch ]($style)"
symbol = "󰊢 "

[git_status]
style = "bold #ffb4ab"
format = "([$all_status$ahead_behind]($style) )"

[character]
success_symbol = "[❯](bold #b1c5ff)"
error_symbol = "[❯](bold #ffb4ab)"

[time]
disabled = false
style = "bold #8f9099"
format = "[$time]($style)"
time_format = "%T"

[cmd_duration]
style = "bold #c0c6dc"
format = "took [$duration]($style) "
min_time = 2_000