[config]

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell-colors.json'
output_path = '~/.cache/quickshell/matugen.json'

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/matugen-colors.conf'
post_hook = 'killall -SIGUSR1 kitty 2>/dev/null || true'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
post_hook = 'for sh in fish bash zsh; do pkill -WINCH -x "$sh" 2>/dev/null; done; true'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
