-------------------------------
---- SEDLY-RICE HYPRLAND.LUA ----
-------------------------------

require("modules.env")
require("modules.monitors")
require("modules.input")
require("modules.general")
require("modules.decorations")
require("modules.animations")
require("modules.layerrules")
require("modules.windowrules")
require("modules.binds")
require("modules.autostart")

-- Include dynamic colors generated by Matugen if available
local colors = os.getenv("HOME") .. "/.config/hypr/colors.lua"
local f = io.open(colors, "r")
if f then
    f:close()
    package.loaded["colors"] = nil
    pcall(dofile, colors)
end

